# @name get_Users
GET {{host}}Users
Authorization: Bearer {{apiKey}}
###

# @name get_customResources
GET {{host}}CustomResources
Authorization: Bearer {{apiKey}}
###

GET {{host}}routedebug/actiondescriptors
###

GET {{host}}routedebug/scimendpoints
###
